from datetime import datetime, timedelta, timezone

from sqlalchemy.exc import InterfaceError, OperationalError
from sqlalchemy.orm import Session

from app.assets.connectivity import (
    assert_zone_segment_consistent,
    device_location_payload,
    mask_device_msisdn,
    public_zone_id,
    require_direct_zone,
)
from app.core.exceptions import AssetNotFoundError, DatabaseUnavailableError
from app.db.models import Asset, Incident
from app.repositories.assets import AssetRepository
from app.schemas.assets import (
    AssetDetail,
    AssetHealthPoint,
    AssetHealthResponse,
    AssetIncidentListResponse,
    AssetListResponse,
    AssetListSummary,
    AssetSortField,
    AssetSummary,
    AssetType,
    ControlMode,
    DeviceLocation,
    GatewayAttributes,
    MaintenanceFilter,
    MeasurementRange,
    OperationalStatus,
    RelatedIncidentSummary,
    SensorAttributes,
    ValveAttributes,
    ValvePosition,
)
from app.schemas.incidents import Classification, IncidentStatus, SeverityTier, SortOrder
from app.schemas.telemetry import TelemetryRange
from app.services.telemetry import TelemetryService
from app.services.telemetry_constants import DATA_MODE


HEALTH_NOTE = (
    "Recent health is a demonstration series generated by the API for visualization. "
    "It is not live sensor telemetry and is labelled mock_recent_health until TimescaleDB "
    "coverage exists for this asset type."
)

SENSOR_HEALTH_NOTE = (
    "Simulated telemetry stored in TimescaleDB. This is not live field telemetry."
)


def _severity_from_tier(tier: int) -> SeverityTier:
    return SeverityTier(f"tier_{tier}")


def maintenance_state(asset: Asset, now: datetime) -> str:
    if asset.next_maintenance_at is None:
        return "not_scheduled"
    if asset.next_maintenance_at <= now:
        return "due"
    if asset.next_maintenance_at <= now + timedelta(days=30):
        return "upcoming"
    return "scheduled"


def to_related_incident(incident: Incident) -> RelatedIncidentSummary:
    return RelatedIncidentSummary(
        id=incident.incident_number,
        incident_number=incident.incident_number,
        title=incident.title,
        classification=Classification(incident.classification),
        severity=_severity_from_tier(incident.severity_tier),
        status=IncidentStatus(incident.status),
        detected_at=incident.detected_at,
    )


def to_summary(asset: Asset, now: datetime) -> AssetSummary:
    position = ValvePosition(asset.current_position) if asset.current_position else None
    zone = require_direct_zone(asset)
    assert_zone_segment_consistent(asset)
    return AssetSummary(
        id=asset.external_id,
        external_id=asset.external_id,
        name=asset.name,
        asset_type=AssetType(asset.asset_type),
        operational_status=OperationalStatus(asset.operational_status),
        health_score=asset.health_score,
        zone=zone.name,
        zone_id=public_zone_id(zone.code),
        zone_name=zone.name,
        location_label=asset.location_label,
        has_cellular_identity=bool(asset.device_msisdn),
        device_msisdn_masked=mask_device_msisdn(asset.device_msisdn),
        pipeline_segment=asset.pipeline_segment.name if asset.pipeline_segment is not None else None,
        manufacturer=asset.manufacturer,
        model=asset.model,
        battery_pct=asset.battery_pct,
        current_position=position,
        last_seen_at=asset.last_seen_at,
        next_maintenance_at=asset.next_maintenance_at,
        maintenance_state=maintenance_state(asset, now),
    )


def _metadata_list(meta: dict, key: str) -> list:
    value = meta.get(key, [])
    return value if isinstance(value, list) else []


def _metadata_str(meta: dict, key: str) -> str | None:
    value = meta.get(key)
    return str(value) if value else None


def _metadata_datetime(meta: dict, key: str) -> datetime | None:
    value = meta.get(key)
    if isinstance(value, datetime):
        return value
    if isinstance(value, str) and value:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    return None


def to_detail(asset: Asset, related: list[Incident], now: datetime) -> AssetDetail:
    summary = to_summary(asset, now)
    meta = asset.extra_metadata or {}
    sensor = None
    valve = None
    gateway = None
    if asset.asset_type == AssetType.sensor.value:
        ranges = [
            MeasurementRange.model_validate(item)
            for item in _metadata_list(meta, "measurement_ranges")
            if isinstance(item, dict)
        ]
        sensor = SensorAttributes(
            measurement_types=[str(item) for item in _metadata_list(meta, "measurement_types")],
            sampling_interval_seconds=asset.sampling_interval_seconds,
            battery_pct=asset.battery_pct,
            signal_strength_dbm=asset.signal_strength_dbm,
            calibration_date=_metadata_datetime(meta, "calibration_date"),
            measurement_ranges=ranges,
            supported_units=[str(item) for item in _metadata_list(meta, "supported_units")],
        )
    elif asset.asset_type == AssetType.valve.value:
        valve = ValveAttributes(
            current_position=ValvePosition(asset.current_position) if asset.current_position else None,
            control_mode=ControlMode(asset.control_mode) if asset.control_mode else None,
            failsafe_position=_metadata_str(meta, "failsafe_position"),
            actuation_type=_metadata_str(meta, "actuation_type"),
            last_command_at=_metadata_datetime(meta, "last_command_at"),
        )
    else:
        gateway = GatewayAttributes(
            provider=_metadata_str(meta, "network_provider"),
            connection_type=_metadata_str(meta, "connection_type"),
            protocols=[str(item) for item in _metadata_list(meta, "protocols")],
            signal_strength_dbm=asset.signal_strength_dbm,
            packet_delivery_status=_metadata_str(meta, "packet_delivery_status"),
        )
    return AssetDetail(
        **summary.model_dump(),
        serial_number=asset.serial_number,
        firmware_version=asset.firmware_version,
        installed_at=asset.installed_at,
        commissioned_at=asset.commissioned_at,
        latitude=asset.latitude,
        longitude=asset.longitude,
        device_location=DeviceLocation(**device_location_payload(asset)),
        last_maintenance_at=asset.last_maintenance_at,
        control_mode=ControlMode(asset.control_mode) if asset.control_mode else None,
        signal_strength_dbm=asset.signal_strength_dbm,
        sampling_interval_seconds=asset.sampling_interval_seconds,
        sensor=sensor,
        valve=valve,
        gateway=gateway,
        related_incidents=[to_related_incident(item) for item in related],
    )


def summarize_assets(rows: list[Asset], now: datetime) -> AssetListSummary:
    return AssetListSummary(
        total_assets=len(rows),
        online=sum(1 for row in rows if row.operational_status == OperationalStatus.online.value),
        degraded=sum(1 for row in rows if row.operational_status == OperationalStatus.degraded.value),
        offline=sum(1 for row in rows if row.operational_status == OperationalStatus.offline.value),
        maintenance_due=sum(
            1
            for row in rows
            if row.next_maintenance_at is not None and row.next_maintenance_at <= now
        ),
    )


def mock_health_series(asset: Asset) -> list[AssetHealthPoint]:
    anchor = asset.last_seen_at or datetime(2026, 9, 1, 7, 45, tzinfo=timezone.utc)
    seed = sum(ord(character) for character in asset.external_id)
    points: list[AssetHealthPoint] = []
    base_health = asset.health_score if asset.health_score is not None else 80.0
    base_battery = asset.battery_pct if asset.battery_pct is not None else 70.0
    base_signal = asset.signal_strength_dbm if asset.signal_strength_dbm is not None else -75
    for index in range(12):
        timestamp = anchor - timedelta(hours=2 * (11 - index))
        wave = ((seed + index * 7) % 9) - 4
        health = max(0.0, min(100.0, round(base_health + wave * 0.6, 1)))
        if asset.asset_type == AssetType.sensor.value:
            points.append(
                AssetHealthPoint(
                    timestamp=timestamp,
                    health_score=health,
                    battery_pct=max(0.0, min(100.0, round(base_battery - (11 - index) * 0.15, 1))),
                    signal_strength_dbm=base_signal + wave,
                )
            )
        elif asset.asset_type == AssetType.valve.value:
            points.append(
                AssetHealthPoint(
                    timestamp=timestamp,
                    health_score=health,
                    availability_pct=max(90.0, min(100.0, round(99.2 - abs(wave) * 0.4, 1))),
                    position_confirmed=index % 5 != 3 or asset.operational_status == OperationalStatus.online.value,
                )
            )
        else:
            points.append(
                AssetHealthPoint(
                    timestamp=timestamp,
                    health_score=health,
                    signal_strength_dbm=base_signal + wave,
                    packet_delivery_pct=max(90.0, min(100.0, round(99.4 - abs(wave) * 0.35, 1))),
                )
            )
    return points


class AssetService:
    def __init__(self, session: Session) -> None:
        self.repository = AssetRepository(session)
        self.telemetry = TelemetryService(session)

    def list_assets(
        self,
        *,
        asset_type: AssetType | None = None,
        status: OperationalStatus | None = None,
        zone: str | None = None,
        search: str | None = None,
        maintenance: MaintenanceFilter | None = None,
        sort_by: AssetSortField = AssetSortField.health_score,
        sort_order: SortOrder = SortOrder.asc,
    ) -> AssetListResponse:
        now = datetime.now(timezone.utc)
        try:
            filtered = self.repository.list_assets(
                asset_type=asset_type,
                status=status,
                zone=zone,
                search=search,
                maintenance=maintenance,
                sort_by=sort_by,
                sort_order=sort_order,
                now=now,
            )
            census = self.repository.list_assets(now=now, sort_by=AssetSortField.name, sort_order=SortOrder.asc)
        except (OperationalError, InterfaceError) as exc:
            raise DatabaseUnavailableError from exc
        return AssetListResponse(
            items=[to_summary(row, now) for row in filtered],
            total=len(filtered),
            summary=summarize_assets(census, now),
        )

    def get_asset(self, asset_id: str) -> AssetDetail:
        now = datetime.now(timezone.utc)
        asset = self._load(asset_id)
        related = self.repository.list_related_incidents(asset)
        return to_detail(asset, related, now)

    def get_related_incidents(self, asset_id: str) -> AssetIncidentListResponse:
        asset = self._load(asset_id)
        related = self.repository.list_related_incidents(asset)
        return AssetIncidentListResponse(
            asset_id=asset.external_id,
            items=[to_related_incident(item) for item in related],
            total=len(related),
        )

    def get_health(self, asset_id: str, range_key: str = TelemetryRange.twenty_four_hours.value) -> AssetHealthResponse:
        asset = self._load(asset_id)
        if asset.asset_type != AssetType.sensor.value:
            return AssetHealthResponse(
                asset_id=asset.external_id,
                series_kind="mock_recent_health",
                note=HEALTH_NOTE,
                items=mock_health_series(asset),
                range=None,
                freshness=None,
                last_reading_at=None,
                data_mode="mock_recent_health",
            )
        return self._sensor_health(asset, range_key)

    def _sensor_health(self, asset: Asset, range_key: str) -> AssetHealthResponse:
        start, end, resolved = self.telemetry.resolve_window(range_key, anchor_to_latest=True)
        interval = "raw" if range_key == "1h" else "5m" if range_key == "6h" else "15m"
        history = self.telemetry.history(
            asset.external_id,
            start=start,
            end=end,
            range_key=resolved,
            interval=interval,
            metrics=["pressure", "flow", "temperature", "signal", "packet_loss", "battery"],
        )
        latest = self.telemetry.latest(asset.external_id)
        items = [
            AssetHealthPoint(
                timestamp=sample.time,
                health_score=_sensor_health_score(sample.battery_pct, sample.packet_loss_pct),
                battery_pct=sample.battery_pct,
                signal_strength_dbm=sample.signal_strength_dbm,
                packet_delivery_pct=round(100.0 - sample.packet_loss_pct, 2)
                if sample.packet_loss_pct is not None
                else None,
                pressure_kpa=sample.pressure_kpa,
                flow_lps=sample.flow_lps,
                packet_loss_pct=sample.packet_loss_pct,
                temperature_c=sample.temperature_c,
            )
            for sample in history.items
        ]
        return AssetHealthResponse(
            asset_id=asset.external_id,
            series_kind="sensor_readings",
            note=SENSOR_HEALTH_NOTE,
            items=items,
            range=resolved,
            freshness=latest.freshness.value,
            last_reading_at=latest.time,
            data_mode=DATA_MODE,
        )

    def sensor_counts(self) -> tuple[int, int]:
        try:
            return self.repository.sensor_counts()
        except (OperationalError, InterfaceError) as exc:
            raise DatabaseUnavailableError from exc

    def _load(self, asset_id: str) -> Asset:
        try:
            row = self.repository.get_by_external_id(asset_id)
        except (OperationalError, InterfaceError) as exc:
            raise DatabaseUnavailableError from exc
        if row is None:
            raise AssetNotFoundError(asset_id)
        return row


def _sensor_health_score(battery_pct: float | None, packet_loss_pct: float | None) -> float:
    battery = battery_pct if battery_pct is not None else 80.0
    loss = packet_loss_pct if packet_loss_pct is not None else 0.0
    return max(0.0, min(100.0, round(battery * 0.5 + (100.0 - loss) * 0.5, 1)))
