import type { AgentAuditEventDetail, AgentAuditRunDetail } from "../types/agentAudit";
import type { AgentFindingRecord, AgentRecommendationRecord, AgentRunDetail } from "../types/integrations";

export function auditRun(overrides: Partial<AgentAuditRunDetail> = {}): AgentAuditRunDetail {
  return {
    id: "run-uuid",
    public_id: "AGRUN-000001",
    agent_code: "investigation_agent",
    agent_type: "investigation_agent",
    contract_version: "1.0",
    pipeline_stages: [],
    source_type: "investigation_batch",
    source_public_id: "batch-demo",
    status: "succeeded",
    classification: "confirmed_anomaly",
    investigation_severity: 3,
    decision: null,
    duration_ms: 65,
    started_at: "2026-09-09T22:49:12.919984Z",
    related_incident: null,
    related_detection: null,
    related_device: null,
    external_cluster_id: "cluster-desert-042",
    data_mode: "simulated",
    blocked: false,
    contract_unconfirmed: false,
    mapping_status: "unmapped",
    events: [],
    findings: [],
    recommendation_decisions: [],
    valve_command_sent: false,
    valve_command_confirmed: false,
    notification_sent: false,
    safety_status: null,
    note: "Ingested agent result. Advisory only.",
    ...overrides,
  };
}

export function auditEvent(overrides: Partial<AgentAuditEventDetail> = {}): AgentAuditEventDetail {
  return {
    id: "evt-1",
    public_id: "AAE-000001",
    agent_run_id: "AGRUN-000001",
    agent_code: "investigation_agent",
    contract_version: "1.0",
    pipeline_stage: "anomaly_investigation",
    node_name: "cluster-review",
    sequence_number: 1,
    event_type: "finding_recorded",
    status: "succeeded",
    summary: "Investigation finding stored",
    incident_public_id: null,
    detection_public_id: null,
    asset_public_id: null,
    external_cluster_id: "cluster-desert-042",
    external_device_id: null,
    error_code: null,
    error_message: null,
    duration_ms: 12,
    data_mode: "simulated",
    occurred_at: "2026-09-09T22:49:12.000Z",
    reasoning_summary: null,
    input_summary: {},
    output_summary: {},
    reasoning_trace: [],
    safety_checks: [],
    ...overrides,
  };
}

export function findingRecord(overrides: Partial<AgentFindingRecord> = {}): AgentFindingRecord {
  return {
    id: "finding-1",
    run_id: "AGRUN-000001",
    provider: "investigation_agent",
    external_anomaly_id: "e048d424-6a15-47ed-a35c-b3cc4c5ff445",
    classification: "confirmed_anomaly",
    classification_label: "Agent-assessed anomaly",
    severity_tier: 3,
    severity_label: "Tier 3",
    confidence_score: 0.9078,
    external_cluster_id: "cluster-desert-042",
    external_segment_id: "seg-neom-north-01",
    external_valve_id: "valve-neom-north-01",
    mapped_detection_id: null,
    mapped_sensor_id: null,
    mapped_segment_id: null,
    mapped_valve_id: null,
    mapping_status: "unmapped",
    review_status: "unread",
    network_status: {
      camara_reachability_status: "REACHABLE",
      camara_congestion_level: "LOW",
      api_unavailable: false,
    },
    physical_deviations: {
      pressure_drop_pct: 36.6071,
      flow_surge_pct: 40.2743,
      pressure_slope: -1.9033,
      flow_slope: 3.9317,
      is_stale_pre_outage_data: false,
    },
    criticality_metrics: {
      criticality_score: 3,
      proximity_to_reservoir_m: 120,
      population_served: 45000,
      associated_valve_id: "valve-neom-north-01",
      pipe_diameter_mm: 400,
    },
    operator_justification: "Operator justification **text**",
    advisory: true,
    data_mode: "simulated",
    created_at: "2026-09-09T22:49:12.919984Z",
    ...overrides,
  };
}

export function recommendationRecord(overrides: Partial<AgentRecommendationRecord> = {}): AgentRecommendationRecord {
  return {
    id: "rec-1",
    run_id: "AGRUN-000002",
    provider: "response_agent",
    external_result_id: "res-demo-001",
    external_incident_id: "INC-1835",
    external_cluster_id: "cluster-desert-042",
    external_device_id: "valve-neom-north-01",
    mapped_incident_number: null,
    mapped_device_id: null,
    incident_attached: false,
    severity_tier: 2,
    severity_label: "Tier 2",
    decision: "ALERT_AND_AWAIT",
    reachability: { status: "REACHABLE" },
    notification_sent: false,
    notification_verified: false,
    valve_command_sent: false,
    valve_command_confirmed: false,
    valve_command_verified: false,
    human_override_requested: true,
    human_override_response: null,
    reasoning_trace: [{ step: "reachability_check" }, { step: "llm_response_planner" }],
    safety_status: "advisory",
    advisory: true,
    data_mode: "simulated",
    created_at: "2026-09-01T07:45:00Z",
    ...overrides,
  };
}

export function integrationRun(overrides: Partial<AgentRunDetail> = {}): AgentRunDetail {
  return {
    run_id: "AGRUN-000001",
    agent_type: "investigation_agent",
    status: "succeeded",
    source_type: "investigation_batch",
    source_public_id: "batch-demo",
    started_at: "2026-09-09T22:49:12.919984Z",
    completed_at: "2026-09-09T22:49:12.984984Z",
    duration_ms: 65,
    data_mode: "simulated",
    mapping_warning_count: 4,
    error_code: null,
    correlation_id: "corr",
    idempotency_key: "investigation:batch-demo",
    contract_version: "1.0",
    request_payload: { batch_id: "batch-demo" },
    response_payload: {
      schema_version: "1.0",
      data_mode: "simulated",
      batch: {
        batch_id: "batch-demo",
        analysis_timestamp: "2026-08-31T02:00:00Z",
        total_clusters_analyzed: 3,
        anomalies_detected_count: 3,
        investigated_threats: [],
      },
    },
    validation_errors: [],
    mapping_warnings: [
      {
        code: "agent_identity_unmapped",
        entity_type: "sensor_cluster",
        external_id: "cluster-desert-042",
        message: "No configured mapping exists for this external identity.",
      },
    ],
    error_message: null,
    ...overrides,
  };
}
